framework:
    rate_limiter:
        signup_ip:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minute'
            cache_pool: cache.rate_limiter
        signup_email:
            policy: 'fixed_window'
            limit: 10
            interval: '1 hour'
            cache_pool: cache.rate_limiter
        resend_email:
            policy: 'fixed_window'
            limit: 1
            interval: '10 minutes'
            cache_pool: cache.rate_limiter
        verify_token:
            policy: 'sliding_window'
            limit: 10
            interval: '1 minute'
            cache_pool: cache.rate_limiter
        password_reset_ip:
            policy: 'fixed_window'
            limit: 10
            interval: '1 hour'
            cache_pool: cache.rate_limiter
        password_reset_email:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
            cache_pool: cache.rate_limiter
        password_reset_confirm:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minute'
            cache_pool: cache.rate_limiter
