<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250918142828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blocks (blocker_user_id UUID NOT NULL, blocked_user_id UUID NOT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(blocker_user_id, blocked_user_id))');
        $this->addSql('CREATE INDEX IDX_CEED9578C1668098 ON blocks (blocker_user_id)');
        $this->addSql('CREATE INDEX IDX_CEED95781EBCBB63 ON blocks (blocked_user_id)');
        $this->addSql('COMMENT ON COLUMN blocks.blocker_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN blocks.blocked_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN blocks.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE conversations (id UUID NOT NULL, match_id UUID NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, last_msg_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C2521BF12ABEACD6 ON conversations (match_id)');
        $this->addSql('COMMENT ON COLUMN conversations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN conversations.match_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN conversations.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN conversations.last_msg_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE interests (id UUID NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8B405EA5E237E06 ON interests (name)');
        $this->addSql('COMMENT ON COLUMN interests.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN interests.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE matches (id UUID NOT NULL, user_a_id UUID NOT NULL, user_b_id UUID NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62615BA415F1F91 ON matches (user_a_id)');
        $this->addSql('CREATE INDEX IDX_62615BA53EAB07F ON matches (user_b_id)');
        $this->addSql('COMMENT ON COLUMN matches.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN matches.user_a_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN matches.user_b_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN matches.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE media_assets (id UUID NOT NULL, user_id UUID NOT NULL, storage_key TEXT NOT NULL, url TEXT DEFAULT NULL, kind TEXT DEFAULT \'photo\' NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, blurhash TEXT DEFAULT NULL, is_public BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C5A8E750A76ED395 ON media_assets (user_id)');
        $this->addSql('COMMENT ON COLUMN media_assets.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.deleted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE message_receipts (message_id UUID NOT NULL, recipient_id UUID NOT NULL, delivered_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, seen_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(message_id, recipient_id))');
        $this->addSql('CREATE INDEX IDX_14CD27B3537A1329 ON message_receipts (message_id)');
        $this->addSql('CREATE INDEX IDX_14CD27B3E92F8F78 ON message_receipts (recipient_id)');
        $this->addSql('COMMENT ON COLUMN message_receipts.message_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN message_receipts.recipient_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN message_receipts.delivered_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN message_receipts.seen_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE messages (id UUID NOT NULL, conversation_id UUID NOT NULL, sender_id UUID NOT NULL, media_id UUID DEFAULT NULL, message_type VARCHAR(255) DEFAULT \'text\' NOT NULL, body TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, edited_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DB021E969AC0396 ON messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96EA9FDD75 ON messages (media_id)');
        $this->addSql('COMMENT ON COLUMN messages.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN messages.conversation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN messages.sender_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN messages.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN messages.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messages.edited_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messages.deleted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE notification_settings (user_id UUID NOT NULL, push_enabled BOOLEAN DEFAULT true NOT NULL, email_enabled BOOLEAN DEFAULT true NOT NULL, sms_enabled BOOLEAN DEFAULT false NOT NULL, per_type JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(user_id))');
        $this->addSql('COMMENT ON COLUMN notification_settings.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification_settings.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE notifications (id UUID NOT NULL, user_id UUID NOT NULL, type VARCHAR(255) NOT NULL, channel VARCHAR(255) DEFAULT \'in_app\' NOT NULL, title TEXT DEFAULT NULL, body TEXT DEFAULT NULL, data JSON DEFAULT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, read_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('COMMENT ON COLUMN notifications.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifications.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.read_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE pricing_plan_prices (id UUID NOT NULL, plan_id UUID NOT NULL, billing_period TEXT NOT NULL, currency VARCHAR(3) NOT NULL, amount_cents INT NOT NULL, stripe_price_id TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19D128AD8B531BD4 ON pricing_plan_prices (stripe_price_id)');
        $this->addSql('CREATE INDEX IDX_19D128ADE899029B ON pricing_plan_prices (plan_id)');
        $this->addSql('COMMENT ON COLUMN pricing_plan_prices.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pricing_plan_prices.plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pricing_plan_prices.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE pricing_plans (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, features JSON DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1995105077153098 ON pricing_plans (code)');
        $this->addSql('COMMENT ON COLUMN pricing_plans.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pricing_plans.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE profile_photos (user_id UUID NOT NULL, media_id UUID NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, position SMALLINT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(user_id, media_id))');
        $this->addSql('CREATE INDEX IDX_605C87BEA76ED395 ON profile_photos (user_id)');
        $this->addSql('CREATE INDEX IDX_605C87BEEA9FDD75 ON profile_photos (media_id)');
        $this->addSql('COMMENT ON COLUMN profile_photos.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN profile_photos.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN profile_photos.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE refresh_tokens (id SERIAL NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE reports (id UUID NOT NULL, reporter_id UUID NOT NULL, reported_user_id UUID NOT NULL, handled_by UUID DEFAULT NULL, reason_code TEXT NOT NULL, details TEXT DEFAULT NULL, status TEXT DEFAULT \'open\' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, closed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F11FA745E1CFE6F5 ON reports (reporter_id)');
        $this->addSql('CREATE INDEX IDX_F11FA745E7566E ON reports (reported_user_id)');
        $this->addSql('CREATE INDEX IDX_F11FA74553689D12 ON reports (handled_by)');
        $this->addSql('COMMENT ON COLUMN reports.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reports.reporter_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reports.reported_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reports.handled_by IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reports.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reports.closed_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE role (id SERIAL NOT NULL, name VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE subscriptions (id UUID NOT NULL, user_id UUID NOT NULL, plan_price_id UUID NOT NULL, stripe_customer_id TEXT DEFAULT NULL, stripe_subscription_id TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, current_period_start TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, current_period_end TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, cancel_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, canceled_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, trial_start TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, trial_end TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4778A01B5DBB761 ON subscriptions (stripe_subscription_id)');
        $this->addSql('CREATE INDEX IDX_4778A01A76ED395 ON subscriptions (user_id)');
        $this->addSql('CREATE INDEX IDX_4778A01D871F09D ON subscriptions (plan_price_id)');
        $this->addSql('COMMENT ON COLUMN subscriptions.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.plan_price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.current_period_start IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.current_period_end IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.cancel_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.canceled_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.trial_start IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.trial_end IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.started_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE swipes (id UUID NOT NULL, actor_user_id UUID NOT NULL, target_user_id UUID NOT NULL, action VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B4DF8DAE859B83FF ON swipes (actor_user_id)');
        $this->addSql('CREATE INDEX IDX_B4DF8DAE6C066AFE ON swipes (target_user_id)');
        $this->addSql('COMMENT ON COLUMN swipes.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN swipes.actor_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN swipes.target_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN swipes.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE transactions (id UUID NOT NULL, user_id UUID NOT NULL, subscription_id UUID DEFAULT NULL, stripe_payment_intent_id TEXT DEFAULT NULL, stripe_charge_id TEXT DEFAULT NULL, stripe_invoice_id TEXT DEFAULT NULL, currency VARCHAR(3) NOT NULL, amount_cents INT NOT NULL, status VARCHAR(255) NOT NULL, raw_payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EAA81A4CA76ED395 ON transactions (user_id)');
        $this->addSql('CREATE INDEX IDX_EAA81A4C9A1887DC ON transactions (subscription_id)');
        $this->addSql('COMMENT ON COLUMN transactions.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN transactions.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN transactions.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN transactions.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE user_email_verification_tokens (id UUID NOT NULL, user_id UUID NOT NULL, token_hash VARCHAR(128) NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C4B66C24B3BC57DA ON user_email_verification_tokens (token_hash)');
        $this->addSql('CREATE INDEX idx_verification_user ON user_email_verification_tokens (user_id)');
        $this->addSql('COMMENT ON COLUMN user_email_verification_tokens.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_email_verification_tokens.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_email_verification_tokens.expires_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_email_verification_tokens.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_email_verification_tokens.consumed_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE user_interests (id UUID NOT NULL, user_id UUID NOT NULL, interest_id UUID NOT NULL, weight SMALLINT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C854880EA76ED395 ON user_interests (user_id)');
        $this->addSql('CREATE INDEX IDX_C854880E5A95FF89 ON user_interests (interest_id)');
        $this->addSql('COMMENT ON COLUMN user_interests.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_interests.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_interests.interest_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_interests.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE user_locations (id UUID NOT NULL, user_id UUID NOT NULL, recorded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, geohash TEXT DEFAULT NULL, point geography(POINT, 4326) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1706C75EA76ED395 ON user_locations (user_id)');
        $this->addSql('CREATE INDEX idx_user_locations_point ON user_locations (point)');
        $this->addSql('COMMENT ON COLUMN user_locations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_locations.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_locations.recorded_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE user_profiles (id UUID NOT NULL, user_id UUID NOT NULL, display_name VARCHAR(100) DEFAULT NULL, birthdate DATE DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, orientation VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, job_title VARCHAR(120) DEFAULT NULL, company VARCHAR(160) DEFAULT NULL, education VARCHAR(160) DEFAULT NULL, height_cm INT DEFAULT NULL, lifestyle_json JSON DEFAULT NULL, preferences_json JSON DEFAULT NULL, visibility VARCHAR(255) DEFAULT \'everyone\' NOT NULL, photo_verification BOOLEAN DEFAULT false NOT NULL, location_accuracy_m INT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BBD6130A76ED395 ON user_profiles (user_id)');
        $this->addSql('COMMENT ON COLUMN user_profiles.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_profiles.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_profiles.birthdate IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_profiles.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_profiles.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(255) NOT NULL, email_normalized VARCHAR(255) NOT NULL, password TEXT NOT NULL, password_algo TEXT DEFAULT \'argon2id\' NOT NULL, phone_e164 VARCHAR(20) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, verification_level VARCHAR(255) DEFAULT \'unverified\' NOT NULL, last_login_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9D5AE72C8 ON users (email_normalized)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.last_login_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.deleted_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE TABLE user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('COMMENT ON COLUMN user_roles.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED9578C1668098 FOREIGN KEY (blocker_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED95781EBCBB63 FOREIGN KEY (blocked_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF12ABEACD6 FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA415F1F91 FOREIGN KEY (user_a_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE matches ADD CONSTRAINT FK_62615BA53EAB07F FOREIGN KEY (user_b_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_assets ADD CONSTRAINT FK_C5A8E750A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_receipts ADD CONSTRAINT FK_14CD27B3537A1329 FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_receipts ADD CONSTRAINT FK_14CD27B3E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96EA9FDD75 FOREIGN KEY (media_id) REFERENCES media_assets (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_settings ADD CONSTRAINT FK_B0559860A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pricing_plan_prices ADD CONSTRAINT FK_19D128ADE899029B FOREIGN KEY (plan_id) REFERENCES pricing_plans (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_photos ADD CONSTRAINT FK_605C87BEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_photos ADD CONSTRAINT FK_605C87BEEA9FDD75 FOREIGN KEY (media_id) REFERENCES media_assets (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E7566E FOREIGN KEY (reported_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA74553689D12 FOREIGN KEY (handled_by) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A01A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_4778A01D871F09D FOREIGN KEY (plan_price_id) REFERENCES pricing_plan_prices (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE swipes ADD CONSTRAINT FK_B4DF8DAE859B83FF FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE swipes ADD CONSTRAINT FK_B4DF8DAE6C066AFE FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_email_verification_tokens ADD CONSTRAINT FK_C4B66C24A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_interests ADD CONSTRAINT FK_C854880EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_interests ADD CONSTRAINT FK_C854880E5A95FF89 FOREIGN KEY (interest_id) REFERENCES interests (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_locations ADD CONSTRAINT FK_1706C75EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_profiles ADD CONSTRAINT FK_6BBD6130A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED9578C1668098');
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED95781EBCBB63');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF12ABEACD6');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA415F1F91');
        $this->addSql('ALTER TABLE matches DROP CONSTRAINT FK_62615BA53EAB07F');
        $this->addSql('ALTER TABLE media_assets DROP CONSTRAINT FK_C5A8E750A76ED395');
        $this->addSql('ALTER TABLE message_receipts DROP CONSTRAINT FK_14CD27B3537A1329');
        $this->addSql('ALTER TABLE message_receipts DROP CONSTRAINT FK_14CD27B3E92F8F78');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96EA9FDD75');
        $this->addSql('ALTER TABLE notification_settings DROP CONSTRAINT FK_B0559860A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE pricing_plan_prices DROP CONSTRAINT FK_19D128ADE899029B');
        $this->addSql('ALTER TABLE profile_photos DROP CONSTRAINT FK_605C87BEA76ED395');
        $this->addSql('ALTER TABLE profile_photos DROP CONSTRAINT FK_605C87BEEA9FDD75');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E1CFE6F5');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E7566E');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA74553689D12');
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_4778A01A76ED395');
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_4778A01D871F09D');
        $this->addSql('ALTER TABLE swipes DROP CONSTRAINT FK_B4DF8DAE859B83FF');
        $this->addSql('ALTER TABLE swipes DROP CONSTRAINT FK_B4DF8DAE6C066AFE');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4CA76ED395');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4C9A1887DC');
        $this->addSql('ALTER TABLE user_email_verification_tokens DROP CONSTRAINT FK_C4B66C24A76ED395');
        $this->addSql('ALTER TABLE user_interests DROP CONSTRAINT FK_C854880EA76ED395');
        $this->addSql('ALTER TABLE user_interests DROP CONSTRAINT FK_C854880E5A95FF89');
        $this->addSql('ALTER TABLE user_locations DROP CONSTRAINT FK_1706C75EA76ED395');
        $this->addSql('ALTER TABLE user_profiles DROP CONSTRAINT FK_6BBD6130A76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('DROP TABLE blocks');
        $this->addSql('DROP TABLE conversations');
        $this->addSql('DROP TABLE interests');
        $this->addSql('DROP TABLE matches');
        $this->addSql('DROP TABLE media_assets');
        $this->addSql('DROP TABLE message_receipts');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE notification_settings');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE pricing_plan_prices');
        $this->addSql('DROP TABLE pricing_plans');
        $this->addSql('DROP TABLE profile_photos');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE reports');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE subscriptions');
        $this->addSql('DROP TABLE swipes');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE user_email_verification_tokens');
        $this->addSql('DROP TABLE user_interests');
        $this->addSql('DROP TABLE user_locations');
        $this->addSql('DROP TABLE user_profiles');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_roles');
    }
}
