# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Enum/'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true

     # DTO
    App\Dto\:
        resource: '../src/Dto'
        autowire: true
        autoconfigure: true

    # State (processors, providers, etc.)
    App\State\:
        resource: '../src/State'
        autowire: true
        autoconfigure: true
    App\State\LocationDataTransformer:
        arguments:
            - '@api_platform.doctrine.orm.state.persist_processor'
            - '@logger'

    App\EventSubscriber\SecurityHeadersSubscriber:
        arguments:
            $environment: '%kernel.environment%'

    App\Security\EmailVerificationManager:
        arguments:
            $resendLimiter: '@limiter.resend_email'
            $verifyLimiter: '@limiter.verify_token'
            $hmacKey: '%env(string:EMAIL_VERIFICATION_HMAC_KEY)%'
            $frontendVerifyUrl: '%env(string:FRONTEND_VERIFY_URL)%'
            $fromAddress: '%env(string:MAILER_FROM_ADDRESS)%'
            $fromName: '%env(string:MAILER_FROM_NAME)%'

    App\Security\PasswordResetManager:
        arguments:
            $requestEmailLimiter: '@limiter.password_reset_email'
            $requestIpLimiter: '@limiter.password_reset_ip'
            $confirmLimiter: '@limiter.password_reset_confirm'
            $hmacKey: '%env(string:PASSWORD_RESET_HMAC_KEY)%'
            $frontendResetUrl: '%env(string:FRONTEND_PASSWORD_RESET_URL)%'
            $fromAddress: '%env(string:MAILER_FROM_ADDRESS)%'
            $fromName: '%env(string:MAILER_FROM_NAME)%'

    App\Security\UserAccountChecker: ~

    App\State\UserPasswordProcessor:
        arguments:
            $signupIpLimiter: '@limiter.signup_ip'
            $signupEmailLimiter: '@limiter.signup_email'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
