

### user login

POST https://localhost/v1/api/login
Content-Type: application/ld+json

{
  "email": "utilisateur_test@loveconnect.com",
  "password": "Martinique-/po93"
}

### user refresh
POST https://localhost/v1/api/refresh/token
Content-Type: application/ld+json

{
  "refresh_token": "2bb4e8fffd0ae61e873c8a63a63d2aceacda6f7356ae0c5c4e15c2ea9d0f49c4ba32e164b10885746e32515374a4c8f507e2bade1e5175b76dd55e994de3af84"
}

### user email verify
GET https://localhost/v1/api/email/verify?token=NUsWZVxwwui4ZOeDIPMCw9O7pUghcYD1hfXWV7U1V9Y

### user email resend
POST https://localhost/v1/api/email/resend
Content-Type: application/json

{
  "email": "utilisateur_test@loveconnect.com"
}

### password reset request
POST https://localhost/v1/api/password/reset/request
Content-Type: application/json

{
  "email": "utilisateur_test@loveconnect.com"
}

### password reset confirm
POST https://localhost/v1/api/password/reset/confirm
Content-Type: application/json

{
  "token": "dRzle3Vsyfuq0U9OTlTL0sHvjNCVV1yyWFoFExjrPhc",
  "password": "Martinique-/po93"
}

### user all

get https://localhost/api/users
Content-Type: application/ld+json

### user create
POST https://localhost/api/users
Content-Type: application/ld+json

{
  "email": "utilisateur_test@loveconnect.com",
  "plainPassword": "Martinique-/po93",
  "username": "mon_nouvel_utilisateur",
  "userProfile": {
    "displayName": "Profil de Test",
    "birthdate": "1995-03-20T00:00:00Z",
    "gender": "male",
    "orientation": "straight",
    "bio": "Ceci est une biographie de test pour le nouvel utilisateur.",
    "jobTitle": "Développeur Symfony",
    "company": "LoveConnect",
    "education": "Master en informatique",
    "heightCm": 185,
    "lifestyleJson": [
      "sport",
      "musique"
    ],
    "preferencesJson": [
      "cinema",
      "lecture"
    ],
    "visibility": "everyone",
    "photoVerification": false,
    "locationAccuracyM": 50
  },
  "userLocations": [
     {
      "latitude": 48.8566,
      "longitude": 2.3522,
      "geohash": "u09tvm"
    }
  ],
  "userInterests": [
    {
      "interest": "/api/interests/01995dfa-82c2-7f8f-95db-a3e3ca8d8f15",
      "weight": 1
    },
    {
      "interest": "/api/interests/01995dfa-82c3-7ec7-9677-a248ea491c1f",
      "weight": 1
    }
  ]
}
